// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package authors

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	// 可以为正数/负数
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// 必须是正数
	Amount    int64
	CreatedAt time.Time
}
